/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 20-Feb-2020 21:49:25
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
/*
 * 5hz
 */
const int numTaps = 64;
float32_t fir_coeff[64] = {
		   3.10854216e-06,2.828976676e-06,-6.137980563e-06,-3.111174374e-05,-6.885101175e-05,
		  -9.405141464e-05,-5.791089279e-05,8.986752073e-05,0.0003535714932,0.0006388770416,
		  0.0007375382702,0.0003935027053,-0.0005392885651,-0.001902213437,-0.003119593021,
		  -0.003302571131,-0.001630378771, 0.002084014006, 0.006906634197,   0.0107169468,
		    0.01080931816, 0.005120501388,-0.006329352502, -0.02046317421, -0.03130331635,
		   -0.03154340014,  -0.0151979886,   0.0196067933,  0.06890144944,   0.1231352687,
		     0.1696254909,   0.1964636296,   0.1964636296,   0.1696254909,   0.1231352687,
		    0.06890144944,   0.0196067933,  -0.0151979886, -0.03154340014, -0.03130331635,
		   -0.02046317421,-0.006329352502, 0.005120501388,  0.01080931816,   0.0107169468,
		   0.006906634197, 0.002084014006,-0.001630378771,-0.003302571131,-0.003119593021,
		  -0.001902213437,-0.0005392885651,0.0003935027053,0.0007375382702,0.0006388770416,
		  0.0003535714932,8.986752073e-05,-5.791089279e-05,-9.405141464e-05,-6.885101175e-05,
		  -3.111174374e-05,-6.137980563e-06,2.828976676e-06, 3.10854216e-06
};
