/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 20-Feb-2020 21:49:25
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
/*
 * 5hz
 */
const int numTaps = 64;
float32_t fir_coeff[64] = {
		0.0004220511182, 0.001293076435,-0.001508774702,-0.0006704986445, 0.002517378889,
		  -0.0009000941645,-0.002719495213, 0.003130625002, 0.001373320585,-0.005092629232,
		    0.00179963687, 0.005377871916,-0.006128364708,-0.002663768129, 0.009798535146,
		  -0.003439222695, -0.01022350416,  0.01160979737, 0.005039576441, -0.01856073365,
		   0.006543327123,  0.01961284876, -0.02256907895,-0.009990792722,  0.03784262016,
		   -0.01387927216, -0.04399437085,  0.05486571416,  0.02738250792,  -0.1255657226,
		    0.06519341469,   0.5141040087,   0.5141040087,  0.06519341469,  -0.1255657226,
		    0.02738250792,  0.05486571416, -0.04399437085, -0.01387927216,  0.03784262016,
		  -0.009990792722, -0.02256907895,  0.01961284876, 0.006543327123, -0.01856073365,
		   0.005039576441,  0.01160979737, -0.01022350416,-0.003439222695, 0.009798535146,
		  -0.002663768129,-0.006128364708, 0.005377871916,  0.00179963687,-0.005092629232,
		   0.001373320585, 0.003130625002,-0.002719495213,-0.0009000941645, 0.002517378889,
		  -0.0006704986445,-0.001508774702, 0.001293076435,0.0004220511182
};
